### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by thezoggy** [aforty/sabnzbd-knockstrap#3]
my two cents, feel free to ignore if you want :)

using latest version of firefox, noticed that the top nav ui doesn't really do much.. i would assume it should have loaded a different view (history/queue/home) but it doesn't.. so i thought it should at least jump down to where it is on the page.. it doesn't. told it to restart and you don't get any indication that its doing anything.. looks like a interesting start of a theme.. but that's what it feels like.. just a partial theme for right now. 

the responsive ui works great when you are really changing devices, not so much when your on a desktop and your just changing the browser size. should adapt that to be a little smarter. desktop resolution and desktop app's viewpoint are two different things. 

anyways if you wanna talk more jump on the sabnzbd channel.

**Comment by aforty** [comment]
I appreciate the feedback.

Restart progress I've been meaning to do for a while and I admit to being guilty on neglecting Firefox as a browser. So I'll definitely look into both of those.

In regards to responsive, are you saying it's not working correctly in certain browser size? What are you thinking the functionality should be?

**Comment by thezoggy** [comment]
bootstrap's responsive for the navbar is a bit over zealous at being responsive... make your browser half your screen and you see that its collapsed and puts the navbar into a dropdown list.. however if this didnt happen the actual navbar would have been able to be fully shown. thus it was collapsed for no reason. the media queries need to be adjusted.

**Comment by aforty** [comment]
Fair point. By default they collapse for tablet sizes which made sense for me initially. Good feedback, I'll look into these. Feel free to comment if you have anything else.
